module.exports = [
  {
    userId: "6901cade7c4165825a862837",
    company: "Google Philippines",
    role: "Junior Software Engineer",
    platform: "LinkedIn",
    status: "Applied",
    priority: "Top Choice",
    types: "Tech Company",
    notes: "Dream company — applied for graduate program.",
  },
  {
    userId: "6901cade7c4165825a862837",
    company: "Accenture",
    role: "Full Stack Developer",
    platform: "JobStreet",
    status: "Interview Scheduled",
    priority: "Top Choice",
    types: "Tech Company",
    notes: "Initial interview scheduled next week.",
  },
  {
    userId: "6901cade7c4165825a862837",
    company: "Globe Telecom",
    role: "Frontend Developer",
    platform: "Referral",
    status: "Offer Received",
    priority: "Consider",
    types: "Tech Company",
    notes: "Offer received but salary slightly below expectation.",
  },
  {
    userId: "6901cade7c4165825a862837",
    company: "Department of Information and Communications Technology (DICT)",
    role: "IT Support Specialist",
    platform: "Email",
    status: "Applied",
    priority: "Neutral",
    types: "Government",
    notes: "Government opening for IT support in regional office.",
  },
  {
    userId: "6901cade7c4165825a862837",
    company: "Sprout Solutions",
    role: "Backend Developer",
    platform: "LinkedIn",
    status: "Rejected",
    priority: "Top Choice",
    types: "Tech Company",
    notes: "Rejected after technical exam, need to improve on databases.",
  },
  {
    userId: "6901cade7c4165825a862837",
    company: "Pointwest Technologies",
    role: "Junior Web Developer",
    platform: "JobStreet",
    status: "Offer Accepted",
    priority: "Top Choice",
    types: "Tech Company",
    notes: "Offer accepted — onboarding soon.",
  },
  {
    userId: "6901cade7c4165825a862837",
    company: "Makati City Government",
    role: "Programmer I",
    platform: "Referral",
    status: "Applied",
    priority: "Consider",
    types: "Government",
    notes: "Referred by previous OJT supervisor; waiting for response.",
  },
  {
    userId: "6901cade7c4165825a862837",
    company: "Amazon Web Services (AWS)",
    role: "Cloud Support Associate",
    platform: "LinkedIn",
    status: "Withdrawn",
    priority: "Neutral",
    types: "Tech Company",
    notes: "Withdrew application after realizing it's for senior-level.",
  },
  {
    userId: "6901cade7c4165825a862837",
    company: "Shopee Philippines",
    role: "Junior Backend Developer",
    platform: "LinkedIn",
    status: "Interview Scheduled",
    priority: "Top Choice",
    types: "Tech Company",
    notes: "Coding interview next Monday.",
  },
  {
    userId: "6901cade7c4165825a862837",
    company: "National Economic and Development Authority (NEDA)",
    role: "Data Analyst",
    platform: "Email",
    status: "Applied",
    priority: "Consider",
    types: "Government",
    notes: "Government analyst position with data visualization tasks.",
  },
];
